name: build
on:
    push:
        branches:
            - main
        paths:
            # Package
            - src/**
            # Workflow
            - .github/workflows/build.yaml
            # TypeScript
            - tsconfig*
              # Dependencies
            - package.json
            - yarn.lock
    pull_request:
        paths:
            # Package
            - src/**
            # Workflow
            - .github/workflows/build.yaml
            # TypeScript
            - tsconfig*
            # Dependencies
            - package.json
            - yarn.lock

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Latest Commit
              uses: actions/checkout@v2

            - name: Restore Dependencies
              uses: actions/cache@v2
              id: dependency-cache
              with:
                  key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
                  path: node_modules

            - name: Install Dependencies
              if: steps.dependency-cache.outputs.cache-hit != 'true'
              run: yarn install

            - name: Run Typecheck
              run: yarn typecheck

            - name: Run Linter
              run: yarn lint

            - name: Run Tests
              run: yarn test

            - name: Build
              run: yarn build
